language: csharp
solution: Expressly.SDK.NET45.csproj

install:
	- sudo apt-get install -y gtk-sharp2
	nuget restore Expressly.SDK.NET45.csproj

mono:
	- latest

script: 
- xbuild /p:Configuration=Release /Source/SDK/Expressly.SDK.NET45.csproj
