language: csharp

install:
    - sudo apt-get install -y gtk-sharp2

mono:
    - latest

script: 
    - nuget restore ./Source/SDK/Expressly.SDK.NET45.csproj
    - xbuild ./Source/SDK/Expressly.SDK.NET45.csproj