language: csharp

install:
    - sudo apt-get install -y gtk-sharp2
    - nuget restore ./Source/Expressly.SDK.NET45.sln

mono:
    - latest

script: 
    - xbuild ./Source/SDK/Expressly.SDK.NET45.csproj