version: 1.1.2.{build}
init: 
  - git config --global core.autocrlf true 
branches:
  only:
  - master
nuget:
  project_feed: true
before_build:
- nuget restore C:\projects\expressly-plugin-sdk-dotnet-core\Source\Expressly.SDK.NET45.sln
build:
  project: C:\projects\expressly-plugin-sdk-dotnet-core\Source\Expressly.SDK.NET45.sln
#  verbosity: minimal
after_test:
  - cmd: C:\projects\expressly-plugin-sdk-dotnet-core\Source\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:"nunit3-console.exe" -targetargs:"C:\projects\expressly-plugin-sdk-dotnet-core\Source\Tests\bin\Debug\net45\Expressly.Tests.dll" -filter:"+[Expressly]* -[Expressly]Expressly.Log.* -[Expressly]Expressly.Testing.Log" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:Expressly_coverage.xml
  - cmd: "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - cmd: pip install codecov
  - cmd: codecov -f "Expressly_coverage.xml" -X gcov --token=286d10e2-dc26-46e5-a026-47cc897ed19b
