version: 1.1.2.{build}
branches:
  only:
  - master
nuget:
  project_feed: true
before_build:
- nuget restore C:\projects\expressly-plugin-sdk-dotnet-core\Source\Expressly.SDK.NET45.sln
build:
  project: C:\projects\expressly-plugin-sdk-dotnet-core\Source\Expressly.SDK.NET45.sln
  verbosity: minimal
after_test:
  - C:\projects\expressly-plugin-sdk-dotnet-core\Source\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user "-target:C:\projects\expressly-plugin-sdk-dotnet-core\Source\packages\NUnit.Console.3.0.1\tools\nunit3-console.exe" -targetargs:"C:\projects\expressly-plugin-sdk-dotnet-core\Source\Tests\bin\Debug\net45\Expressly.Tests.dll" -filter:"+[Expressly.*]* -[Expressly.Log]* -[Expressly.Test]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:Expressly_coverage.xml
   - pip install codecov
   - codecov -f "Expressly_coverage.xml"
