version: 1.1.2.{build}
branches:
  only:
  - master
nuget:
  project_feed: true
#before_build:
#- cmd: nuget restore ./Source/Expressly.SDK.NET45.sln
build:
  project: C:\projects\expressly-plugin-sdk-dotnet-core\Sample\Expressly.SDK.NET45.sln
  verbosity: minimal
