version: 1.1.2.{build}
branches:
  only:
  - master
nuget:
  project_feed: true
before_build:
- nuget restore
build:
  project: C:\projects\expressly-plugin-sdk-dotnet-core\Source\Expressly.SDK.NET45.sln
  verbosity: minimal
